// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/iam.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbcc987c0695300, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbcc987c0695300, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "api.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "api.LoginResponse")
}

func init() { proto.RegisterFile("api/iam.proto", fileDescriptor_4dbcc987c0695300) }

var fileDescriptor_4dbcc987c0695300 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x80, 0xe1, 0x2c, 0x14, 0x1b, 0xf2, 0xd0, 0x12, 0x21, 0x9e, 0xc2, 0x53, 0x27, 0x8b, 0x3a,
	0x17, 0x75, 0x0c, 0xf2, 0xe2, 0x1b, 0x4c, 0xb8, 0xc4, 0x62, 0x3a, 0x93, 0xb3, 0xd2, 0xeb, 0x47,
	0xab, 0x84, 0xc7, 0x7f, 0x17, 0xbe, 0x99, 0x81, 0x08, 0xd9, 0xec, 0x0c, 0xd6, 0x19, 0xb7, 0x64,
	0x49, 0xcd, 0x90, 0x4d, 0x7a, 0x81, 0xc5, 0x9d, 0x9e, 0xa6, 0x29, 0xf4, 0xbb, 0xd3, 0x62, 0xd5,
	0x0a, 0x7c, 0x5d, 0xa3, 0x79, 0xc5, 0xde, 0xc6, 0xdb, 0xce, 0x8b, 0x3e, 0x54, 0x02, 0x21, 0xa3,
	0xc8, 0x87, 0xda, 0x32, 0x9e, 0xba, 0x8f, 0x7f, 0xa7, 0x27, 0x88, 0x06, 0x41, 0x98, 0x1a, 0xd1,
	0x6a, 0x0d, 0x81, 0x58, 0xb4, 0x9d, 0x38, 0x23, 0x2c, 0x86, 0xfa, 0xd1, 0x96, 0x2a, 0xdd, 0x0c,
	0x42, 0x1f, 0x87, 0x33, 0x40, 0x6e, 0x2a, 0x64, 0x2a, 0x6f, 0xd7, 0x5c, 0xed, 0xc1, 0x77, 0x98,
	0x5a, 0x66, 0xc8, 0x26, 0x1b, 0xaf, 0x96, 0xa8, 0xf1, 0x53, 0x3f, 0x2b, 0x9d, 0x3c, 0x02, 0x77,
	0xcc, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x25, 0xd7, 0xb7, 0x85, 0xdd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MikapodIAMClient is the client API for MikapodIAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MikapodIAMClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type mikapodIAMClient struct {
	cc *grpc.ClientConn
}

func NewMikapodIAMClient(cc *grpc.ClientConn) MikapodIAMClient {
	return &mikapodIAMClient{cc}
}

func (c *mikapodIAMClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/api.MikapodIAM/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MikapodIAMServer is the server API for MikapodIAM service.
type MikapodIAMServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedMikapodIAMServer can be embedded to have forward compatible implementations.
type UnimplementedMikapodIAMServer struct {
}

func (*UnimplementedMikapodIAMServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterMikapodIAMServer(s *grpc.Server, srv MikapodIAMServer) {
	s.RegisterService(&_MikapodIAM_serviceDesc, srv)
}

func _MikapodIAM_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikapodIAMServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MikapodIAM/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikapodIAMServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MikapodIAM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MikapodIAM",
	HandlerType: (*MikapodIAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MikapodIAM_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam.proto",
}
